Add loopback ip to referrer check if it is not bound to app server
zowe/zlux-server-framework pull request #269
Opened 2021-02-22 09:39 UTC by timgerstel

This pull request implements the following feature:
- Add loopback ip to referrer check if it exists but is not set to bind to the app servers IP array

Signed-off-by: Timothy Gerstel <tgerstel@rocketsoftware.com>

2021-02-22 19:02 UTC, 1000TurquoisePogs requested changes
This will not fix the error, but I have a suggestion.
Real error:
Code hits line 1296 `return res.status(403).send('Forbidden due to referrer');` 
It happens because the loopback request has no referrer header, and then the code did not recognize the request as coming from loopback because the IP did not match `this.loopbackConfig.host`

loopbackConfig.host gets set here
https://github.com/zowe/zlux-server-framework/blob/staging/lib/util.js#L309

There are a few problems to fix
* use of https://github.com/zowe/zlux-server-framework/blob/staging/lib/util.js#L284 becomes odd because the purpose of it was to determine which ip is loopback from a list of IPs given. But, the caller now knows what the loopback really is, if it is explicitly specified.

* one way or another, this.loopbackConfig.host must be config.node.loopbackIp if specified.
Two ways come to mind
1) change getLoopbackAddress(listenerAddresses) to getLoopbackAddress(listenerAddresses, nodeConfig) which will allow it to return the right loopback ip given that it can now read the full config
2) dont change it, but conditionally call it depending on whether or not loopbackIp was explicitly specified

* dont read env vars directly in this code. always read config such as config.node.loopbackIp ... env gets translated to config in the other PR https://github.com/zowe/zlux-app-server/pull/143

* ensure that specification of loopbackIp does not necessarily mean to bind to it, as in https://github.com/zowe/zlux-app-server/pull/143

2021-02-22 19:49 UTC, timgerstel commented
>     * dont read env vars directly in this code. always read config such as config.node.loopbackIp ... env gets translated to config in the other PR [zowe/zlux-app-server#143](https://github.com/zowe/zlux-app-server/pull/143)
> 

But env vars are used throughout the rest of the code block? https://github.com/zowe/zlux-server-framework/pull/269/files#diff-eaecb33c0e784a4fb1b89c027e9b17fcdcd349e386abcbb4584f187927794598R1249

The other PR assigns the loopback IP to the ipAddresses array which would mean if that order ever changes it would affect this functionality, assuming the best way to distinguish ZOWE_LOOPBACK_ADDRESS in `ZWED_node_https_ipAddresses="${ZOWE_LOOPBACK_ADDRESS},${ZOWE_IP_ADDRESS}",` would just be to reference the first element of the array.

2021-02-22 20:55 UTC, 1000TurquoisePogs commented
The use of env vars in that code block is also incorrect. Things should stem from the config object so that there is no confusion about where config is coming from. Just 1 place. On the outside, several (env, cli, json file) are mapped to 1 config object, so its the job of convert-env.sh to handle that complexity so that this code can remain simple and flexible.

The other PR assigns the loopback IP to the array CONDITIONALLY, and the particular error we saw was to be fixed on the condition that the loopback IP actually is not added to the array. So, 2 different cases here and we're solving both.

2021-02-24 00:24 UTC, 1000TurquoisePogs approved these changes

2021-02-24 00:26 UTC, merged